/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.8.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
/** Gets an object describing a particular variant of content. */
export function getContentType(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/GetContentType/" + params.type + "/"
    });
}
/** Returns a content item referenced by id */
export function getContentById(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/GetContentById/" + params.id + "/" + params.locale + "/",
        params: {
            head: params.head
        }
    });
}
/** Returns the newest item that matches a given tag and Content Type. */
export function getContentByTagAndType(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/GetContentByTagAndType/" + params.tag + "/" + params.type + "/" + params.locale + "/",
        params: {
            head: params.head
        }
    });
}
/**
 * Gets content based on querystring information passed in. Provides basic search
 * and text search capabilities.
 */
export function searchContentWithText(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/Search/" + params.locale + "/",
        params: {
            ctype: params.ctype,
            currentpage: params.currentpage,
            head: params.head,
            searchtext: params.searchtext,
            source: params.source,
            tag: params.tag
        }
    });
}
/** Searches for Content Items that match the given Tag and Content Type. */
export function searchContentByTagAndType(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/SearchContentByTagAndType/" + params.tag + "/" + params.type + "/" + params.locale + "/",
        params: {
            currentpage: params.currentpage,
            head: params.head,
            itemsperpage: params.itemsperpage
        }
    });
}
/** Search for Help Articles. */
export function searchHelpArticles(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/SearchHelpArticles/" + params.searchtext + "/" + params.size + "/"
    });
}
