"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.3
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/** Gets an object describing a particular variant of content. */
function getContentType(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/GetContentType/" + params.type + "/"
    });
}
exports.getContentType = getContentType;
/** Returns a content item referenced by id */
function getContentById(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/GetContentById/" + params.id + "/" + params.locale + "/",
        params: {
            head: params.head
        }
    });
}
exports.getContentById = getContentById;
/** Returns the newest item that matches a given tag and Content Type. */
function getContentByTagAndType(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/GetContentByTagAndType/" + params.tag + "/" + params.type + "/" + params.locale + "/",
        params: {
            head: params.head
        }
    });
}
exports.getContentByTagAndType = getContentByTagAndType;
/**
 * Gets content based on querystring information passed in. Provides basic search
 * and text search capabilities.
 */
function searchContentWithText(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/Search/" + params.locale + "/",
        params: {
            ctype: params.ctype,
            currentpage: params.currentpage,
            head: params.head,
            searchtext: params.searchtext,
            source: params.source,
            tag: params.tag
        }
    });
}
exports.searchContentWithText = searchContentWithText;
/** Searches for Content Items that match the given Tag and Content Type. */
function searchContentByTagAndType(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Content/SearchContentByTagAndType/" + params.tag + "/" + params.type + "/" + params.locale + "/",
        params: {
            currentpage: params.currentpage,
            head: params.head,
            itemsperpage: params.itemsperpage
        }
    });
}
exports.searchContentByTagAndType = searchContentByTagAndType;
