"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.8.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/** Claim a partner offer as the authenticated user. */
function claimPartnerOffer(http, body) {
    return http({
        method: 'POST',
        url: 'https://www.bungie.net/Platform/Tokens/Partner/ClaimOffer/',
        body: body
    });
}
exports.claimPartnerOffer = claimPartnerOffer;
/**
 * Apply a partner offer to the targeted user. This endpoint does not claim a new
 * offer, but any already claimed offers will be applied to the game if not already.
 */
function applyMissingPartnerOffersWithoutClaim(http, params) {
    return http({
        method: 'POST',
        url: "https://www.bungie.net/Platform/Tokens/Partner/ApplyMissingOffers/" + params.partnerApplicationId + "/" + params.targetBnetMembershipId + "/"
    });
}
exports.applyMissingPartnerOffersWithoutClaim = applyMissingPartnerOffersWithoutClaim;
/**
 * Returns the partner sku and offer history of the targeted user. Elevated
 * permissions are required to see users that are not yourself.
 */
function getPartnerOfferSkuHistory(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Tokens/Partner/History/" + params.partnerApplicationId + "/" + params.targetBnetMembershipId + "/"
    });
}
exports.getPartnerOfferSkuHistory = getPartnerOfferSkuHistory;
