export var BungieCredentialType = {
  None: 0,
  Xuid: 1,
  Psnid: 2,
  Wlid: 3,
  Fake: 4,
  Facebook: 5,
  Google: 8,
  Windows: 9,
  DemonId: 10,
  SteamId: 12,
  BattleNetId: 14,
  StadiaId: 16,
  TwitchId: 18,
  EgsId: 20,
};
export var OptInFlags = {
  None: 0,
  Newsletter: 1,
  System: 2,
  Marketing: 4,
  UserResearch: 8,
  CustomerService: 16,
  Social: 32,
  PlayTests: 64,
  PlayTestsLocal: 128,
  Careers: 256,
};
