/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */
import { GeneralUser, PublicPartnershipDetail, UserAlias, UserMembershipData, UserTheme } from './interfaces';
import { PlatformErrorCodes } from '../common';
export interface GeneralUserServerResponse {
    readonly Response?: GeneralUser;
    readonly ErrorCode?: PlatformErrorCodes;
    readonly ThrottleSeconds?: number;
    readonly ErrorStatus?: string;
    readonly Message?: string;
    readonly MessageData?: {
        [key: string]: string;
    };
}
export interface ListOfUserAliasServerResponse {
    readonly Response?: UserAlias[];
    readonly ErrorCode?: PlatformErrorCodes;
    readonly ThrottleSeconds?: number;
    readonly ErrorStatus?: string;
    readonly Message?: string;
    readonly MessageData?: {
        [key: string]: string;
    };
}
export interface ListOfGeneralUserServerResponse {
    readonly Response?: GeneralUser[];
    readonly ErrorCode?: PlatformErrorCodes;
    readonly ThrottleSeconds?: number;
    readonly ErrorStatus?: string;
    readonly Message?: string;
    readonly MessageData?: {
        [key: string]: string;
    };
}
export interface ListOfUserThemeServerResponse {
    readonly Response?: UserTheme[];
    readonly ErrorCode?: PlatformErrorCodes;
    readonly ThrottleSeconds?: number;
    readonly ErrorStatus?: string;
    readonly Message?: string;
    readonly MessageData?: {
        [key: string]: string;
    };
}
export interface UserMembershipDataServerResponse {
    readonly Response?: UserMembershipData;
    readonly ErrorCode?: PlatformErrorCodes;
    readonly ThrottleSeconds?: number;
    readonly ErrorStatus?: string;
    readonly Message?: string;
    readonly MessageData?: {
        [key: string]: string;
    };
}
export interface CEListOfPublicPartnershipDetailServerResponse {
    readonly Response?: PublicPartnershipDetail[];
    readonly ErrorCode?: PlatformErrorCodes;
    readonly ThrottleSeconds?: number;
    readonly ErrorStatus?: string;
    readonly Message?: string;
    readonly MessageData?: {
        [key: string]: string;
    };
}
