/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.5
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */

import * as AppImport from './app';
import * as UserImport from './user';
import * as ForumImport from './forum';
import * as GroupV2Import from './groupv2';
import * as Destiny2Import from './destiny2';
import * as CommunityContentImport from './communitycontent';
import * as TrendingImport from './trending';

export const App = AppImport;
export const User = UserImport;
export const Forum = ForumImport;
export const GroupV2 = GroupV2Import;
export const Destiny2 = Destiny2Import;
export const CommunityContent = CommunityContentImport;
export const Trending = TrendingImport;
