"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.5
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/** Returns community content. */
function getCommunityContent(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/CommunityContent/Get/" + params.sort + "/" + params.mediaFilter + "/" + params.page + "/"
    });
}
exports.getCommunityContent = getCommunityContent;
/** Returns info about community members who are live streaming. */
function getCommunityLiveStatuses(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/CommunityContent/Live/All/" + params.partnershipType + "/" + params.sort + "/" + params.page + "/",
        params: {
            modeHash: params.modeHash,
            streamLocale: params.streamLocale
        }
    });
}
exports.getCommunityLiveStatuses = getCommunityLiveStatuses;
/** Returns info about community members who are live streaming in your clans. */
function getCommunityLiveStatusesForClanmates(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/CommunityContent/Live/Clan/" + params.partnershipType + "/" + params.sort + "/" + params.page + "/"
    });
}
exports.getCommunityLiveStatusesForClanmates = getCommunityLiveStatusesForClanmates;
/** Returns info about community members who are live streaming among your friends. */
function getCommunityLiveStatusesForFriends(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/CommunityContent/Live/Friends/" + params.partnershipType + "/" + params.sort + "/" + params.page + "/"
    });
}
exports.getCommunityLiveStatusesForFriends = getCommunityLiveStatusesForFriends;
/** Returns info about Featured live streams. */
function getFeaturedCommunityLiveStatuses(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/CommunityContent/Live/Featured/" + params.partnershipType + "/" + params.sort + "/" + params.page + "/",
        params: {
            streamLocale: params.streamLocale
        }
    });
}
exports.getFeaturedCommunityLiveStatuses = getFeaturedCommunityLiveStatuses;
/** Gets the Live Streaming status of a particular Account and Membership Type. */
function getStreamingStatusForMember(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/CommunityContent/Live/Users/" + params.partnershipType + "/" + params.membershipType + "/" + params.membershipId + "/"
    });
}
exports.getStreamingStatusForMember = getStreamingStatusForMember;
