/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.8.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
/**
 * Gets a count of all active non-public fireteams for the specified clan. Maximum
 * value returned is 25.
 */
export function getActivePrivateClanFireteamCount(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Fireteam/Clan/" + params.groupId + "/ActiveCount/"
    });
}
/**
 * Gets a listing of all of this clan's fireteams that are have available slots.
 * Caller is not checked for join criteria so caching is maximized.
 */
export function getAvailableClanFireteams(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Fireteam/Clan/" + params.groupId + "/Available/" + params.platform + "/" + params.activityType + "/" + params.dateRange + "/" + params.slotFilter + "/" + params.publicOnly + "/" + params.page + "/",
        params: {
            langFilter: params.langFilter
        }
    });
}
/**
 * Gets a listing of all public fireteams starting now with open slots. Caller is
 * not checked for join criteria so caching is maximized.
 */
export function searchPublicAvailableClanFireteams(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Fireteam/Search/Available/" + params.platform + "/" + params.activityType + "/" + params.dateRange + "/" + params.slotFilter + "/" + params.page + "/",
        params: {
            langFilter: params.langFilter
        }
    });
}
/**
 * Gets a listing of all clan fireteams that caller is an applicant, a member, or
 * an alternate of.
 */
export function getMyClanFireteams(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Fireteam/Clan/" + params.groupId + "/My/" + params.platform + "/" + params.includeClosed + "/" + params.page + "/",
        params: {
            groupFilter: params.groupFilter,
            langFilter: params.langFilter
        }
    });
}
/** Gets a specific clan fireteam. */
export function getClanFireteam(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/Fireteam/Clan/" + params.groupId + "/Summary/" + params.fireteamId + "/"
    });
}
