"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.2.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Get API usage by application for time frame specified. You can go as far back as
 * 30 days ago, and can ask for up to a 48 hour window of time in a single request.
 * You must be authenticated with at least the ReadUserData permission to access
 * this endpoint.
 */
function getApplicationApiUsage(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/App/ApiUsage/" + params.applicationId + "/",
        params: {
            end: params.end,
            start: params.start
        }
    });
}
exports.getApplicationApiUsage = getApplicationApiUsage;
/** Get list of applications created by Bungie. */
function getBungieApplications(http) {
    return http({
        method: 'GET',
        url: 'https://www.bungie.net/Platform/App/FirstParty/'
    });
}
exports.getBungieApplications = getBungieApplications;
