"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.4
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var AppImport = require("./app");
var UserImport = require("./user");
var ContentImport = require("./content");
var ForumImport = require("./forum");
var GroupV2Import = require("./groupv2");
var Destiny2Import = require("./destiny2");
var CommunityContentImport = require("./communitycontent");
var TrendingImport = require("./trending");
var FireteamImport = require("./fireteam");
exports.App = AppImport;
exports.User = UserImport;
exports.Content = ContentImport;
exports.Forum = ForumImport;
exports.GroupV2 = GroupV2Import;
exports.Destiny2 = Destiny2Import;
exports.CommunityContent = CommunityContentImport;
exports.Trending = TrendingImport;
exports.Fireteam = FireteamImport;
