import * as AppImport from './app/index.js';
import * as UserImport from './user/index.js';
import * as ContentImport from './content/index.js';
import * as ForumImport from './forum/index.js';
import * as GroupV2Import from './groupv2/index.js';
import * as TokensImport from './tokens/index.js';
import * as Destiny2Import from './destiny2/index.js';
import * as CommunityContentImport from './communitycontent/index.js';
import * as TrendingImport from './trending/index.js';
import * as FireteamImport from './fireteam/index.js';
import * as SocialImport from './social/index.js';
import * as CoreImport from './core/index.js';
export const App = AppImport;
export const User = UserImport;
export const Content = ContentImport;
export const Forum = ForumImport;
export const GroupV2 = GroupV2Import;
export const Tokens = TokensImport;
export const Destiny2 = Destiny2Import;
export const CommunityContent = CommunityContentImport;
export const Trending = TrendingImport;
export const Fireteam = FireteamImport;
export const Social = SocialImport;
export const Core = CoreImport;