/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.5
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */
import * as AppImport from './app';
import * as UserImport from './user';
import * as ForumImport from './forum';
import * as GroupV2Import from './groupv2';
import * as Destiny2Import from './destiny2';
import * as CommunityContentImport from './communitycontent';
import * as TrendingImport from './trending';
export declare const App: typeof AppImport;
export declare const User: typeof UserImport;
export declare const Forum: typeof ForumImport;
export declare const GroupV2: typeof GroupV2Import;
export declare const Destiny2: typeof Destiny2Import;
export declare const CommunityContent: typeof CommunityContentImport;
export declare const Trending: typeof TrendingImport;
