/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
import * as AppImport from './app/index.js';
import * as UserImport from './user/index.js';
import * as ContentImport from './content/index.js';
import * as ForumImport from './forum/index.js';
import * as GroupV2Import from './groupv2/index.js';
import * as TokensImport from './tokens/index.js';
import * as Destiny2Import from './destiny2/index.js';
import * as CommunityContentImport from './communitycontent/index.js';
import * as TrendingImport from './trending/index.js';
import * as FireteamImport from './fireteam/index.js';
import * as SocialImport from './social/index.js';
import * as CoreImport from './core/index.js';
export declare const App: typeof AppImport;
export declare const User: typeof UserImport;
export declare const Content: typeof ContentImport;
export declare const Forum: typeof ForumImport;
export declare const GroupV2: typeof GroupV2Import;
export declare const Tokens: typeof TokensImport;
export declare const Destiny2: typeof Destiny2Import;
export declare const CommunityContent: typeof CommunityContentImport;
export declare const Trending: typeof TrendingImport;
export declare const Fireteam: typeof FireteamImport;
export declare const Social: typeof SocialImport;
export declare const Core: typeof CoreImport;
