/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.21.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */

import { HttpClient, get, post } from '../http.js';

import {
  BungieCredentialType,
  GeneralUser,
  GetCredentialTypesForAccountResponse,
  HardLinkedUserMembership,
  UserMembershipData,
  UserSearchPrefixRequest,
  UserSearchResponse,
  UserTheme
} from './interfaces.js';
import {
  BungieMembershipType,
  ServerResponse
} from '../common.js';

const API_BASE = "https://www.bungie.net/Platform/User/";

export interface GetBungieNetUserByIdParams {
  /** The requested Bungie.net membership id. */
  id: string;
}

/** Loads a bungienet user by membership id. */
export function getBungieNetUserById(http: HttpClient, params: GetBungieNetUserByIdParams): Promise<ServerResponse<GeneralUser>> {
  return get(http, `${API_BASE}GetBungieNetUserById/${params.id}/`);
}

export interface GetSanitizedPlatformDisplayNamesParams {
  /** The requested membership id to load. */
  membershipId: string;
}

/**
 * Gets a list of all display names linked to this membership id but sanitized (
 * profanity filtered). Obeys all visibility rules of calling user and is heavily
 * cached.
 */
export function getSanitizedPlatformDisplayNames(http: HttpClient, params: GetSanitizedPlatformDisplayNamesParams): Promise<ServerResponse<{ [key in BungieCredentialType]: string }>> {
  return get(http, `${API_BASE}GetSanitizedPlatformDisplayNames/${params.membershipId}/`);
}

export interface GetCredentialTypesForTargetAccountParams {
  /** The user's membership id */
  membershipId: string;
}

/** Returns a list of credential types attached to the requested account */
export function getCredentialTypesForTargetAccount(http: HttpClient, params: GetCredentialTypesForTargetAccountParams): Promise<ServerResponse<GetCredentialTypesForAccountResponse[]>> {
  return get(http, `${API_BASE}GetCredentialTypesForTargetAccount/${params.membershipId}/`);
}

/** Returns a list of all available user themes. */
export function getAvailableThemes(http: HttpClient): Promise<ServerResponse<UserTheme[]>> {
  return get(http, `${API_BASE}GetAvailableThemes/`);
}

export interface GetMembershipDataByIdParams {
  /** The membership ID of the target user. */
  membershipId: string;
  /** Type of the supplied membership ID. */
  membershipType: BungieMembershipType;
}

/**
 * Returns a list of accounts associated with the supplied membership ID and
 * membership type. This will include all linked accounts (even when hidden) if
 * supplied credentials permit it.
 */
export function getMembershipDataById(http: HttpClient, params: GetMembershipDataByIdParams): Promise<ServerResponse<UserMembershipData>> {
  return get(http, `${API_BASE}GetMembershipsById/${params.membershipId}/${params.membershipType}/`);
}

/**
 * Returns a list of accounts associated with signed in user. This is useful for
 * OAuth implementations that do not give you access to the token response.
 */
export function getMembershipDataForCurrentUser(http: HttpClient): Promise<ServerResponse<UserMembershipData>> {
  return get(http, `${API_BASE}GetMembershipsForCurrentUser/`);
}

export interface GetMembershipFromHardLinkedCredentialParams {
  /** The credential to look up. Must be a valid SteamID64. */
  credential: string;
  /** The credential type. 'SteamId' is the only valid value at present. */
  crType: BungieCredentialType;
}

/**
 * Gets any hard linked membership given a credential. Only works for credentials
 * that are public (just SteamID64 right now). Cross Save aware.
 */
export function getMembershipFromHardLinkedCredential(http: HttpClient, params: GetMembershipFromHardLinkedCredentialParams): Promise<ServerResponse<HardLinkedUserMembership>> {
  return get(http, `${API_BASE}GetMembershipFromHardLinkedCredential/${params.crType}/${params.credential}/`);
}

export interface SearchByGlobalNamePrefixParams {
  /** The display name prefix you're looking for. */
  displayNamePrefix: string;
  /** The zero-based page of results you desire. */
  page: number;
}

/** [OBSOLETE] Do not use this to search users, use SearchByGlobalNamePost instead. */
export function searchByGlobalNamePrefix(http: HttpClient, params: SearchByGlobalNamePrefixParams): Promise<ServerResponse<UserSearchResponse>> {
  return get(http, `${API_BASE}Search/Prefix/${params.displayNamePrefix}/${params.page}/`);
}

export interface SearchByGlobalNamePostParams {
  /** The zero-based page of results you desire. */
  page: number;
}

/** Given the prefix of a global display name, returns all users who share that name. */
export function searchByGlobalNamePost(http: HttpClient, params: SearchByGlobalNamePostParams, body: UserSearchPrefixRequest): Promise<ServerResponse<UserSearchResponse>> {
    return post(http, `${API_BASE}Search/GlobalName/${params.page}/`, body);
}
