name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm start

      - name: porcelain check
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: HEAD
          filters: |
            changed:
              - '**'

      - name: Fail if modified files
        if: steps.filter.outputs.changed == 'true'
        run: |
          echo "::error title=Built files not checked in::Make sure to run pnpm start and check in modified files"
          exit 1

      - name: Test
        run: pnpm test
