name: NPM Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    environment: publish
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      # This will only publish if the package.json version has changed
      - name: Check version changes
        uses: EndBug/version-check@v2 # More info about the arguments on the action page
        id: check # This will be the reference for later
        with:
          file-url: https://unpkg.com/bungie-api-ts@latest/package.json
          static-checking: localIsNew

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: Publish the package to NPM
        if: steps.check.outputs.changed == 'true'
        run: cd lib && npm publish --provenance
